services:
  mariadb:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - mariadb_network
    environment:
      - MYSQL_DATABASE=car
      - MYSQL_USER=user
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=user
    ports:
      - 3306:3306
volumes:
  mariadb_data:
networks:
  mariadb_network:
